### PR TITLE
fix(proxy-console): socket.close() → socket.end()

### PR DESCRIPTION
**Pull request by pdonias**

### CODE REVIEW

**Comment by olivierlambert** [comment]
what was the impact of this issue?

**Comment by pdonias** [comment]
xo-server crashed on console's websocket error.

**Comment by olivierlambert** [comment]
ouch! is it an old bug?

**Comment by pdonias** [comment]
Sep 2015, probably.

**Comment by olivierlambert** [comment]
Strange we never noticed it before. Thanks for the fix!

**Pull request merged**
